server:
  port: 8082

jwt:
  # base64 encoded key
  secret: 9i3Bk8SJ3CfqIm+v9JJjHc5PGmqNmevaXDLYX4k0sW9hmhuvA6rTNWIM6uISlbVWcn28bMs+gY+P3LLzRytHMQ==
  # 30min
  secs_to_expire_access: 1800
  # 30days
  secs_to_expire_refresh: 2592000
  # 5min
  secs_to_expire_change_password: 300

oauth2:
  redirect-uris: http://localhost:3000

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: {PROVIDER_NAME_CLIENT_ID}
            client-secret: {PROVIDER_NAME_CLIENT_SECRET}
            redirectUri: "{baseUrl}/auth/oauth2/code/google"
            scope:
              - email
              - profile
